name: TimoliaCore
version: 1.0
author: pizzafreak08
website: http://www.timolia.de/
main: me.pizzafreak08.TimoliaCore.TimoliaCore
commands:
    armor:
        usage: /<command>
    ca:
        usage: /<command>
    cc:
        usage: /<command>
    dump:
        usage: /<command>
    colors:
        usage: /<command>
    visible:
    clock:
    skick:
        usage: /<command>
    timolia:
        usage: /<command>
    raw:
        usage: /<command>
    setloc:
        usage: /<command>
    removeloc:
        usage: /<command>
    loclist:
        usage: /<command>
    mode:
        usage: /<command>
    console:
    exe:
    drop:
    cblock:
    damage:
    listname:
    chat:
    itemname:
    itemlore:
    st:
    loc:
    ctp:
    effect: