name: TimoliaCore
version: 1.0
author: pizzafreak08
website: http://www.timolia.de/
main: de.dariusmewes.TimoliaCore.TimoliaCore
commands:
    access:
        usage: /access <allow/deny> [msg] OR <add/remove> <name> OR <reload/list> OR setmsg <msg>
        description: 
    armor:
        usage: /armor [Player] <slot> <item-id>
        description: 
    asave:
        usage: /asave <start/stop/delay/status>
        description: 
    book:
        usage: /book <author/title> [args]
        description: 
    ca:
        usage: /ca [Player]
        description: 
    cblock:
        usage: /cblock
        description: 
    cc:
        usage: /cc [all/-a]
        description: 
    chat:
        usage: /chat <Player> <msg>
        description: 
    clock:
        usage: /clock
        description: 
    colors:
        usage: /colors [Player]
        description: 
    console:
        usage: /console <cmd>
        description: 
    ctp:
        usage: /ctp <x> <y> <z> [Player]
        description: 
    damage:
        usage: /damage <Player> <amount>
        description: 
    deaths:
        usage: /deaths <on/off/clear>
        description: 
    drop:
        usage: /drop [all/item-id]
        description: 
    dump:
        usage: /dump
        description: 
    effect:
        usage: /effect <add/remove> <effect> <power> <duration> [player]
        description: 
    exe:
        usage: /exe <Spieler> <Befehl>
        description: 
    itemlore:
        usage: /itemlore <add/remove> <name>
        description: 
    itemname:
        usage: /itemname <name>
        description: 
    listname:
        usage: /listname [Player] <Name>
        description: 
    loc:
        usage: /loc <Location> [Player]
        description: 
    loclist:
        usage: /loclist
        description: 
    mode:
        usage: /mode
        description: 
    pingmsg:
        usage: /pingmsg <msg>
        description: 
    raw:
        usage: /raw [-s] <msg>
        description: 
    removeloc:
        usage: /removeloc <Location>
        description: 
    setloc:
        usage: /setloc <name>
        description: 
    skick:
        usage: /skick <Spieler> <msg>
        description: 
    st:
        usage: /st <msg>
        description: 
    tcore:
        usage: /tcore reload
        description: 
    visible:
        usage: /visible [player/all]
        description: 