name: TimoliaCore
version: 1.0
author: pizzafreak08
website: http://www.timolia.de/
main: de.dariusmewes.TimoliaCore.TimoliaCore
commands:
    access:
        usage: /access <allow/deny> [msg] OR <add/remove> <name> OR <reload/list> OR setmsg <msg>
        description: A better whitelist
    armor:
        usage: /armor [Player] <slot> <item-id>
        description: Change your or someone elses armor
    asave:
        usage: /asave <start/stop/delay/status>
        description: Settings for autosaving
    book:
        usage: /book <author/title> [args]
        description: Change the author and title of a book
    ca:
        usage: /ca [Player]
        description: Clear your or someone elses inventory and armor
    cblock:
        usage: /cblock [Player]
        description: Gives you or someone else a commandblock
    cc:
        usage: /cc [all/-a]
        description: Clear your or everyones chat
    chat:a
        usage: /chat <Player> <msg>
        description: Type messages for someone else
    clock:
        usage: /clock
        description: Shows date and time
    colors:
        usage: /colors [Player]
        description: Shows a list of available chat colors
    console:
        usage: /console <cmd>
        description: Executes console-commands
    ctp:
        usage: /ctp <x> <y> <z> [Player]
        description: Teleport yourself or someone else to a certain position. commandblock support
    damage:
        usage: /damage <Player> <amount>
        description: Damage someone else
    deaths:
        usage: /deaths [clear]
        description: Hide deathmessages
    drop:
        usage: /drop [all/item-id]
        description: Drop a certain Material or just everything
    dump:
        usage: /dump
        description: Dump the item in your hand
    exe:
        usage: /exe <Spieler> <Befehl>
        description: Execute a command with all permissions for someone else
    itemlore:
        usage: /itemlore <add/remove> <name>
        description: Change the lore of an item
    itemname:
        usage: /itemname <name>
        description: Change the name of an item
    listname:
        usage: /listname [Player] <Name>
        description: Change your or someone elses playerlistname
    loc:
        usage: /loc <Location> [Player]
        description: Teleport yourself or someone else to a location
    loclist:
        usage: /loclist
        description: Shows a list of Locations
    mode:
        usage: /mode
        description: Switch between Creative and Survival-Mode
    pingmsg:
        usage: /pingmsg <msg>
        description: Change the Message in the Multiplayer-Menu
    raw:
        usage: /raw [-s] <msg>
        description: Broadcast a raw text-message
    removeloc:
        usage: /removeloc <Location>
        description: Remove a Location
    setloc:
        usage: /setloc <name>
        description: Set a Location
    skick:
        usage: /skick <Spieler> <msg>
        description: Kick someone silently
    st:
        usage: /st <msg>
        description: Send Messages to other Staffs
    tcore:
        usage: /tcore reload
        description: Plugin-Managing
    visible:
        usage: /visible [player/all]
        description: Remove someones/everyones invisibility-effect